SELECT CAR.CAR_ID CAR_ID,
       CAR.CAR_TYPE CAR_TYPE,
       CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100 FEE
  FROM CAR_RENTAL_COMPANY_CAR CAR, CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
   WHERE CAR.CAR_TYPE = PLAN.CAR_TYPE(+)
   AND PLAN.DURATION_TYPE = '30일 이상' 
   AND CAR.CAR_TYPE IN ('세단', 'SUV')
   AND CAR.CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE (START_DATE < TO_DATE('2022-11-30 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
           AND END_DATE > TO_DATE('2022-11-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
    )
   AND (CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) / 100) * 30 >= 500000
   AND (CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) / 100) * 30 < 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC;