SELECT CAR.CAR_ID AS CAR_ID, 
       CAR.CAR_TYPE AS CAR_TYPE, 
       CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100 AS FEE
  FROM CAR_RENTAL_COMPANY_CAR CAR
  LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
    ON CAR.CAR_TYPE = PLAN.CAR_TYPE
 WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
   AND PLAN.DURATION_TYPE = '30일 이상'
   AND CAR.CAR_ID NOT IN (
        SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
         WHERE (START_DATE < TO_DATE('2022-11-30 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
           AND END_DATE > TO_DATE('2022-11-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
    )
   AND (CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100) >= 500000
   AND (CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC;
