-- 입양을 간 기록은 있는데 보호소에 들어온 기록이 없는 동물

SELECT OUTS.ANIMAL_ID, OUTS.NAME
  FROM ANIMAL_OUTS OUTS
     , ANIMAL_INS  INS
 WHERE OUTS.ANIMAL_ID = INS.ANIMAL_ID(+)
   AND INS.ANIMAL_ID IS NULL
ORDER BY OUTS.ANIMAL_ID, OUTS.NAME;
