SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
  FROM (SELECT DEV.ID
     , DEV.FIRST_NAME
     , DEV.LAST_NAME
     , DEV.SKILL_CODE
     , DEV.EMAIL
     , SKILL.NAME
     , SKILL.CATEGORY
     , SKILL.CODE
  FROM DEVELOPERS DEV
CROSS JOIN SKILLCODES SKILL) TAB
WHERE ID NOT IN ( 
                SELECT ID
                  FROM DEVELOPERS DEV, SKILLCODES SKILL
                 WHERE DEV.SKILL_CODE = SKILL.CODE
                   AND CATEGORY  = 'Back End')
 AND SKILL_CODE & TAB.CODE
 AND SKILL_CODE >= TAB.CODE
 AND CATEGORY = 'Front End'
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID;