-- 코드를 입력하세요
SELECT BOOK.BOOK_ID BOOK_ID, AUTHOR.AUTHOR_NAME AUTHOR_NAME, TO_CHAR(BOOK.PUBLISHED_DATE,'YYYY-MM-DD') PUBLISHED_DATE
  FROM BOOK
     , AUTHOR
 WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID(+)
   AND BOOK.CATEGORY = '경제'
ORDER BY BOOK.PUBLISHED_DATE;